services:
  backend:
    build:
      dockerfile: Dockerfile.dev
    working_dir: /workspace/backend
    volumes:
      - .:/workspace
    environment:
      DEBUG: "true"

  frontend:
    build:
      dockerfile: Dockerfile.dev
    working_dir: /workspace/frontend
    volumes:
      - .:/workspace
      - frontend_node_modules:/workspace/frontend/node_modules
      - frontend_next:/workspace/frontend/.next

volumes:
  frontend_node_modules:
  frontend_next:
