FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements/requirements.txt requirements/requirements.txt
COPY requirements/requirements-dev.txt requirements/requirements-dev.txt

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements/requirements-dev.txt

COPY . .

CMD ["bash"]