"""add chat topic

Revision ID: cffda4138170
Revises: b8b2b5326af8
Create Date: 2026-08-02 13:46:16.451033

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Alembicが使うリビジョン識別子
revision: str = "cffda4138170"
down_revision: str | Sequence[str] | None = "b8b2b5326af8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """スキーマをこのリビジョンの状態へ進める。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("t_chat", sa.Column("topic", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """スキーマを1つ前のリビジョンの状態へ戻す。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("t_chat", "topic")
    # ### end Alembic commands ###
